apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ujpz4qf74-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ujpz4qf74-java-quarkus-gitops